- name: Add Longhorn stable helm chart repo
  community.kubernetes.helm_repository:
    name: longhorn
    repo_url: "https://charts.longhorn.io"

- name: Deploy longhorn chart
  community.kubernetes.helm:
    name: longhorn
    chart_ref: longhorn/longhorn
    release_namespace: longhorn-system
    create_namespace: yes
    update_repo_cache: "{{ update_helm_repo }}"
    wait: yes
    values_files:
      - "{{working_directory_path}}/longhorn/values.yaml"

- name: Create AWS Secret
  community.kubernetes.k8s:
    state: absent
    src: "{{working_directory_path}}/longhorn/secret.yaml"
